### PR TITLE
Use activation hook to reduce atom loading time

### PR DESCRIPTION
**Pull request by geksilla**

### CODE REVIEW

**Comment by roman01la** [comment]
Wonder how does it work?

**Comment by geksilla** [comment]
It will activate package only when clojure grammar used in active editor.
For more info please check [activationHooks](http://flight-manual.atom.io/hacking-atom/sections/package-word-count/#packagejson) attribute from atom docs.

**Comment by geksilla** [comment]
You can open **Timecop** in atom and check **Package Activation** timeline.

**Comment by roman01la** [comment]
That's interesting. I'm going to test this first. Thanks!

**Pull request merged**
